# 3x3の利得行列から各プレイヤーの混合戦略を求める

In [25]:
from scipy.optimize import minimize
import nashpy as nash
import numpy as np

In [26]:
player_a_payoff_matrix = np.array([[4, -1, -1],
                          [-3, 0, 3],
                          [0, 1, -2]])
player_b_payoff_matrix = np.array([[-4, 1, 1],
                          [3, 0, -3],
                          [0, -1, 2]])
# gameの定義
game = nash.Game(player_a_payoff_matrix, player_b_payoff_matrix)  


equilibrias = game.support_enumeration() 
for eq in equilibrias:
    print(eq)

(array([0.28571429, 0.35714286, 0.35714286]), array([0.21428571, 0.54761905, 0.23809524]))


In [27]:
player_a_payoff_matrix = np.array([[4, -1, -2],
                          [-3, 0, 3],
                          [0, 1, 2]])
player_b_payoff_matrix = np.array([[-4, 1, 2],
                          [3, 0, -3],
                          [0, -1, 2]])
# gameの定義
game = nash.Game(player_a_payoff_matrix, player_b_payoff_matrix)  


equilibrias = game.support_enumeration()  
for eq in equilibrias:
    print(eq)

(array([3.70074342e-17, 2.50000000e-01, 7.50000000e-01]), array([0.25, 0.  , 0.75]))


In [28]:
player_a_payoff_matrix = np.array([[4, -1, -2],
                          [-3, 0, 3],
                          [3, 1, 2]])
player_b_payoff_matrix = np.array([[-4, 1, 2],
                          [3, 0, -3],
                          [-3, -1, -2]])
# gameの定義
game = nash.Game(player_a_payoff_matrix, player_b_payoff_matrix)  


equilibrias = game.support_enumeration()  
for eq in equilibrias:
    print(eq)

(array([0., 0., 1.]), array([0., 1., 0.]))
